# Multi monitor support
bind = $mainMod CTRL, left, movecurrentworkspacetomonitor, l
bind = $mainMod CTRL, right, movecurrentworkspacetomonitor, r
bind = $mainMod CTRL, O, movecurrentworkspacetomonitor, -1
bind = $mainMod, O, exec, sh -c "~/.local/bin/swap-workspaces.sh focus"  # Swap workspaces (focus)
bind = $mainMod Shift, O, exec, ~/.local/bin/swap-workspaces.sh  # Swap workspaces
