-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + CTRL + V")
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "dms ipc call clipboard toggle" })
hl.unbind("SUPER + Escape")
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "dms ipc call powermenu toggle" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "Lock Screen" })
hl.unbind("SUPER + 0")
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }), { description = "focus workspace 10" })
hl.unbind("SUPER + Apostrophe")
hl.bind("SUPER + Apostrophe", hl.dsp.workspace.toggle_special("magic"), { description = "Focus Special Workspace" })
hl.unbind("SUPER + CTRL + 0")
hl.bind("SUPER + CTRL + 0", hl.dsp.window.move({ workspace = "10", follow = false }), { description = "Move to Workspace (silent) 10" })
hl.unbind("SUPER + CTRL + 1")
hl.bind("SUPER + CTRL + 1", hl.dsp.window.move({ workspace = "1", follow = false }), { description = "Move to Workspace (silent) 1" })
hl.unbind("SUPER + CTRL + 2")
hl.bind("SUPER + CTRL + 2", hl.dsp.window.move({ workspace = "2", follow = false }), { description = "Move to Workspace (silent) 2" })
hl.unbind("SUPER + CTRL + 3")
hl.bind("SUPER + CTRL + 3", hl.dsp.window.move({ workspace = "3", follow = false }), { description = "Move to Workspace (silent) 3" })
hl.unbind("SUPER + CTRL + 4")
hl.bind("SUPER + CTRL + 4", hl.dsp.window.move({ workspace = "4", follow = false }), { description = "Move to Workspace (silent) 4" })
hl.unbind("SUPER + CTRL + 5")
hl.bind("SUPER + CTRL + 5", hl.dsp.window.move({ workspace = "5", follow = false }), { description = "Move to Workspace (silent) 5" })
hl.unbind("SUPER + CTRL + 6")
hl.bind("SUPER + CTRL + 6", hl.dsp.window.move({ workspace = "6", follow = false }), { description = "Move to Workspace (silent) 6" })
hl.unbind("SUPER + CTRL + 7")
hl.bind("SUPER + CTRL + 7", hl.dsp.window.move({ workspace = "7", follow = false }), { description = "Move to Workspace (silent) 7" })
hl.unbind("SUPER + CTRL + 8")
hl.bind("SUPER + CTRL + 8", hl.dsp.window.move({ workspace = "8", follow = false }), { description = "Move to Workspace (silent) 8" })
hl.unbind("SUPER + CTRL + 9")
hl.bind("SUPER + CTRL + 9", hl.dsp.window.move({ workspace = "9", follow = false }), { description = "Move to Workspace (silent) 9" })
hl.unbind("SUPER + CTRL + Apostrophe")
hl.bind("SUPER + CTRL + Apostrophe", hl.dsp.window.move({ workspace = "special:magic", follow = false }), { description = "Move to Special Workspace (silent)" })
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.workspace.move({ monitor = "-1" }), { description = "Move to Workspace to another Monitor" })
hl.unbind("SUPER + SHIFT + 0")
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }), { description = "move to workspace 10 (non-silent)" })
hl.unbind("SUPER + SHIFT + Apostrophe")
hl.bind("SUPER + SHIFT + Apostrophe", hl.dsp.window.move({ workspace = "special:magic" }), { description = "Move to Special Workspace" })
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("kitty"), { description = "kitty" })
hl.unbind("SUPER + XF86AudioMute")
hl.bind("SUPER + XF86AudioMute", hl.dsp.exec_cmd("pavucontrol"), { description = "Run Pulseaudio Mixer" })
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("zeal"), { description = "Run zeal" })
hl.unbind("XF86Calculator")
hl.bind("XF86Calculator", hl.dsp.exec_cmd("gnome-calculator"), { description = "Run Calculator" })
hl.unbind("SUPER + CTRL + Q")
hl.bind("SUPER + CTRL + Q", hl.dsp.exit(), { description = "exit" })
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle fullscreen" })
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"), { description = "layoutmsg togglesplit" })
hl.unbind("SUPER + K")
hl.unbind("SUPER + R")
hl.unbind("SUPER + SHIFT + E")
hl.unbind("SUPER + SHIFT + F")
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle maximization" })
hl.unbind("SUPER + SHIFT + O")
hl.unbind("SUPER + T")
hl.unbind("SUPER + U")
hl.bind("SUPER + U", hl.dsp.window.pin(), { description = "Pin Window" })
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
hl.unbind("SUPER + mouse_down")
hl.unbind("SUPER + mouse_up")
hl.unbind("SUPER + Y")
hl.bind("SUPER + Y", hl.dsp.window.pin(), { description = "Pin Window" })
hl.unbind("SHIFT + XF86AudioMute")
hl.bind("SHIFT + XF86AudioMute", hl.dsp.exec_cmd("dms ipc call mic mute"), { locked = true, description = "Microphone Mute Toggle" })
