##! General
bind = Shift, Print, exec, sh -c "dms screenshot" # Screenshot: Region without edit
bind = Super, L, exec, dms ipc call lock lock # Lock Screen
bind = Super Shift, P, exec, sh -c "~/.local/bin/dms-cycle-monitor-profiles.sh" # Output: Change profiles in cycle
bindl = , XF86AudioPlay, exec, dms ipc call mpris playPause # Media: Play/Pause
bind = , XF86Display, exec, sh -c "~/.local/bin/dms-cycle-monitor-profiles.sh" # Output: Change profiles in cycle
bind = , Print, exec, sh -c "$screenshot" # Screenshot: Region

##! DMS Helpers
bind = Ctrl, Escape, exec, dms ipc call processlist toggle # Task Manager: Toggle
bind = Super, Comma, exec, dms ipc call settings toggle # Settings: Toggle
bind = Super, Escape, exec, dms ipc call powermenu toggle # Power Menu: Toggle
bind = Super, R, exec, dms ipc call spotlight toggle # App Launcher: Toggle
bind = Super, Slash, exec, dms ipc call keybinds toggle hyprland # Keybinds Cheatsheet: Toggle
