$screenshot_edit = satty -f - --early-exit --save-after-copy --copy-command=wl-copy --action-on-enter save-to-clipboard -o "$HOME/Pictures/Screenshots/$(date +'screenshot_%Y-%m-%d_%H-%M-%S').png"
$screenshot = dms screenshot region --stdout | $screenshot_edit

unbind = Super, L
unbind = Super, R
unbind = Super, Slash
unbind = , Print
unbind = Shift, Print
unbind = Ctrl, Escape
