# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = [ "d" ]
run = "remove --force"
desc = "Move the files to the trash"

[[manager.prepend_keymap]]
on = [ "Y" ]
run = [
	"shell --confirm --block 'xsel --clipboard < $1'",
]
desc = "Copy file contents"
