[config]

[config.wallpaper]
# Whether to set the wallpaper or not
set = false
command = "awww img --transition-type center {{ image }}"

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.html]
input_path = '~/.config/matugen/templates/template.html'
output_path = '/tmp/matugen-palette.html'

[templates.cosmic]
input_path = '~/.config/matugen/templates/cosmic_theme.ron'
output_path = '~/.config/cosmic/matugen_cosmic.theme.ron'
post_hook = "~/.config/matugen/templates/cosmic_postprocess.py ~/.config/cosmic/matugen_cosmic.theme.ron"
